apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-h13v
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-h13v@sha256:8a244d7d028ce774f2e1689ee4de301d86cb3e9c894b492ae7079a2797d1a8cf
        name: my-nodejs
        resources: {}
status: {}
