apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-h13v
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-h13v
    app.kubernetes.io/part-of: tkrw-pr712-0075-0053-app
  name: devfile-sample-h13v
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-h13v
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-h13v
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-h13v@sha256:8a244d7d028ce774f2e1689ee4de301d86cb3e9c894b492ae7079a2797d1a8cf
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
